name: Hardhat Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Use your project's version
          cache: 'npm'       # Optional: caches dependencies for speed

      - name: Install dependencies
        run: npm install

      - name: Run Hardhat tests
        run: npx hardhat test
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}