name: hardhat-test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardhat unit test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Environment
      uses: actions/setup-node@v3
    # Remove if necessary.
    - name: Foundry
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Show Forge version
      run: |
          forge --version
    # Remove if necessary.
    - name: Test-1
      uses: ambersun1234/hardhat-test-action@v1
      with:
        network: hardhat
    - name: Test-2
      uses: ambersun1234/hardhat-test-action@v1
      with:
        network: arbitrumSepolia
        private_key: ${{ secrets.PRIVATE_KEY }}
        rpc_url: ${{ secrets.RPC_URL }}
        run: npx hardhat test